### PR TITLE
change in site structure

### PR DESCRIPTION
**Pull request by isabelalv**
Changed the overall structure of the site. There are now several pages instead of having everything in the home page. The language used in the home page and the new syllabus page is a rough draft, please feel free to modify it.

### CODE REVIEW

**Comment by rohitmusti** [comment]
The pull request looks really really good! I think you did a really great job splitting up the website into separate sections.

Could you just add the course overview to the top of the syllabus section? That is the only small detail I saw that I was hoping to see changed! If you are too busy tonight, I can go ahead and add it and then merge it in.

**Comment by isabelalv** [comment]
Thank you! I'm glad you liked it. I actually saw your syllabus today and I think I like that style better. I was thinking of switching your syllabus page for mine after removing the weekly breakdown (since it would be redundant with the lessons page) and adding the course overview at the top if it's not already there. What do you think?

**Comment by rohitmusti** [comment]
I like the idea! I will update your PR branch and then let you know when it is ready to be reviewed by you before pulling into master (I agree that the weekly breakdown is redundant given the layout you came up with).

Do you think we should still keep a separate contact the instructors page? I think it is helpful to have that listed independently and was thinking about adding a link to it on the syllabus page.

**Comment by isabelalv** [comment]
I think a separate contact page will be useful, especially if we decide to have a "class wide" email account (for you, me and Professor Tychonievich). And it could also have individual contact information, of course.

**Pull request merged**
